project/urls.py
from django.contrib import admin
from django.urls import path, include
import sightings.views as views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('map/', views.show_map, name='show_map'),
    path('sightings/', include('sightings.urls')),
]

sightings/urls.py
from django.urls import path

from . import views

app_name = 'sightings'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('stats/', views.stats, name='stats'),
    path('<squirrel_id>/', views.detail, name='detail'),
]

sightings/models.py
from django.db import models
from django.utils.translation import gettext as _


class Squirrel(models.Model):
    # Latitude #
    X = models.FloatField(
        max_length=10,
        help_text=_('Latitude'),
    )

    # Longitude #
    Y = models.FloatField(
        max_length=10,
        help_text=_('Longitude'),
    )

    # Unique Squirrel ID #
    Squirrel_ID = models.CharField(
        max_length=100,
        help_text=_('Unique Squirrel ID'),
        primary_key=True,
        default = None,
    )
    
    # Shift #
    AM = 'AM'
    PM = 'PM'
    
    SHIFT_CHOICES = [
        (AM,_('AM')),
        (PM,_('PM')),
    ]

    Shift = models.CharField(
        max_length=100,
        help_text=_('Shift'),
        choices=SHIFT_CHOICES,
        blank=True,
    )
    
    # Date #
    Date = models.DateField(
        help_text=_('Date'),
        blank=True,
    )
    
    # Age #
    Adult = 'Adult'
    Juvenile = 'Juvenile'

    AGE_CHOICES = [
        (Adult,_('Adult')),
        (Juvenile,_('Juvenile')),
    ]

    Age = models.CharField(
        max_length=15,
        help_text=_('Age'),
        choices=AGE_CHOICES,
        blank=True,
        null=True,
    )
    
    # Primary Fur Color #
    Gray = 'Gray'
    Cinnamon = 'Cinnamom'
    Black = 'Black'
    
    COLOR_CHOICES = [
        (Gray,_('Gray')),
        (Cinnamon,_('Cinnamom')),
        (Black,_('Black')),
    ]

    Primary_Fur_Color = models.CharField(
        max_length=100,
        help_text=_('Primary Fur Color'),
        choices=COLOR_CHOICES,
        blank=True,
        null=True,
    )
    
    # Location #
    Above_Ground = 'Above Ground'
    Ground_Plane = 'Ground Plane'

    LOCATION_CHOICES = [
        (Above_Ground,_('Above Ground')),
        (Ground_Plane,_('Ground Plane')),
    ]

    Location = models.CharField(
        max_length=100,
        help_text=_('Location'),
        choices=LOCATION_CHOICES,
        blank=True,
        null=True,
    )
    
    # Specific Location #
    Specific_Location = models.CharField(
        max_length=100,
        help_text=_('Specific Location'),
        blank=True,
        null=True,
    )
    
    # Running #
    Running = models.BooleanField(
        help_text=_('Whether or not squirrel is running'),
        null=True,
    )
    
    # Chasing #
    Chasing = models.BooleanField(
        help_text=_('Whether or not squirrel is chasing'),
        null=True,
    )
    
    # Climbing #
    Climbing = models.BooleanField(
        help_text=_('Whether or not squirrel is climbing'),
        null=True,
    )
    
    # Eating #
    Eating = models.BooleanField(
        help_text=_('Whether or not squirrel is eating'),
        null=True,
    )
    
    # Foraging #
    Foraging = models.BooleanField(
        help_text=_('Whether or not squirrel is foraging'),
        null=True,
    )
    
    # Other Activities #
    Other_Activities = models.CharField(
        max_length=100,
        help_text=_('Other Activities'),
        blank=True,
        null=True,
    )
    
    # Kuks #
    Kuks = models.BooleanField(
        help_text=_('Kuks'),
        null=True,
    )
    
    # Quaas #
    Quaas = models.BooleanField(
        help_text=_('Quaas'),
        null=True,
    )
    
    # Moans #
    Moans = models.BooleanField(
        help_text=_('Moans'),
        null=True,
    )
    
    # Tail_Flags #
    Tail_Flags = models.BooleanField(
        help_text=_("Whether or not squirrel's tail flag"),
        null=True,
    )
    
    # Tail_Twitches #
    Tail_Twitches = models.BooleanField(
        help_text=_("Whether or not squirrel's tail twitch"),
        null=True,
    )
    
    # Approaches #
    Approaches = models.BooleanField(
        help_text=_('Whether or not squirrel approaches'),
        null=True,
    )
    
    # Indifferent #
    Indifferent = models.BooleanField(
        help_text=_('Whether or not squirrel is indifferent'),
        null=True,
    )
    
    # Runs From #
    Runs_From = models.BooleanField(
        help_text=_('Where the squirrel is running from'),
        null=True,
    )

    def __str__(self):
        return self.Squirrel_ID

sightings/forms.py
from django.forms import ModelForm

from .models import Squirrel


class Form(ModelForm):
    class Meta:
        model = Squirrel
        fields = ['X', 'Y', 'Shift', 'Date', 'Age']


class CreateForm(ModelForm):
    class Meta:
        model = Squirrel
        fields = ['X', 'Y', 'Squirrel_ID',
                  'Shift', 'Date', 'Age',
                  'Primary_Fur_Color', 'Location', 'Specific_Location',
                  'Running', 'Chasing', 'Climbing',
                  'Eating', 'Foraging', 'Other_Activities',
                  'Kuks', 'Quaas', 'Moans',
                  'Tail_Flags', 'Tail_Twitches', 'Approaches',
                  'Indifferent', 'Runs_From']

sightings/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse

from .forms import Form, CreateForm
from .models import Squirrel
from django.db.models import Max,Count,Avg,Min


def index(request):
    squirrels = Squirrel.objects.all()
    context = {
        'squirrels': squirrels
    }
    return render(request, 'sightings/index.html', context)


def detail(request, squirrel_id):
    squirrel = get_object_or_404(Squirrel, Squirrel_ID=squirrel_id)
    if request.method == 'GET':
        # Query detail of the squirrel
        form = Form(instance=squirrel)
        context = {
            'form': form,
            'squirrel_id': squirrel_id
        }
        return render(request, 'sightings/edit.html', context)
    if request.method == 'POST':
        # Edit detail of the squirrel
        form = Form(request.POST, instance=squirrel)
        if form.is_valid():
            form.save()
            context = {
                'form': form,
                'squirrel_id': squirrel_id,
                'success': True
            }
            return render(request, 'sightings/edit.html', context)
        else:
            return HttpResponse('Form data is invalid, invalid fields: ' + form.errors)
    return HttpResponse('Method not supported.')


def show_map(request):
    sightings = Squirrel.objects.all()[:100]
    context = {
        'sightings': sightings
    }
    return render(request, 'sightings/map.html', context)


def add(request):
    if request.method == 'GET':
        # Return form
        form = CreateForm()
        context = {
            'form': form
        }
        return render(request, 'sightings/add.html', context)
    if request.method == 'POST':
        # Save the data of the new squirrel
        form = CreateForm(request.POST)
        if form.is_valid():
            form.save()
            context = {
                'form': form,
                'success': True
            }
            return render(request, 'sightings/add.html', context)
        else:
            return HttpResponse('Form data is invalid, invalid fields: ' + form.errors)
    return HttpResponse('Method not supported.')


def stats(request):
    # Get stats of all squirrels
    if request.method == 'GET': 
        context = {
            'squirrels': Squirrel.objects.all(),
            'data_count':Squirrel.objects.all().aggregate(Count('Squirrel_ID'))["Squirrel_ID__count"],
            'Age_Adult_count':Squirrel.objects.filter(Age = "Adult").count(),
            'Age_Juvenile_count':Squirrel.objects.filter(Age = "Juvenile").count(),
            'Date_max':Squirrel.objects.all().aggregate(Max('Date'))["Date__max"],
            'Date_min':Squirrel.objects.all().aggregate(Min('Date'))["Date__min"],
            'Shift_AM_count':Squirrel.objects.filter(Shift = "AM").count(),
            'Shift_PM_count':Squirrel.objects.filter(Shift = "PM").count(),          
            'Location_GP_count':Squirrel.objects.filter(Location = "Ground Plane").count(),
            'Location_AG_count':Squirrel.objects.filter(Location = "Above Ground").count(),     
            'Color_Gray_count':Squirrel.objects.filter(Primary_Fur_Color = "Gray").count(),
            'Color_Cinnamon_count':Squirrel.objects.filter(Primary_Fur_Color = "Cinnamon").count(),
            'Color_Black_count':Squirrel.objects.filter(Primary_Fur_Color = "Black").count(),
            }
        return render(request, 'sightings/stats.html', context)
    return HttpResponse('Method not supported.')    

sightings/templates/sightings/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New sighting</title>
</head>
    <body>
    <h3>New sighting</h3>
	<form method="post">{% csrf_token %}
		{{form.as_p}}
		<br>
		<input type="submit" name="Submit" value="Submit">
        <input type="button" value="Back" onclick="document.location.href = '{% url 'sightings:index' %}'">
	</form>
    {% if success %}
        <p style="color: red">Saved successfully</p>
    {% endif %}
    </body>
</html>

sightings/templates/sightings/detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Detail</title>
    </head>
    <body>
	   {% for squirrel in squirrels %}
	    <p>
	    <h3>Following informations are the detail information for squirrel under ID: {{ squirrel.Squirrel_ID }}</h3>
	    <ul>
		    <li>Logitude: {{ squirrel.X }}</li>
		    <li>Latitude: {{ squirrel.Y }}</li>
		    <li>Shift: {{ squirrel.Shift }}</li>
		    <li>Date: {{ squirrel.Date }}</li>
		    <li>Age: {{ squirrel.Age }}</li>
		    <li>Primary Fur Color: {{  squirrel.Primary_Fur_Color  }}</li>
		    <li>Location : {{ squirrel.Location }}</li>
		    <li>Specific Location: {{ squirrel.Specific_Location }}</li>
		    <li>Running: {{ squirrel.Running }}</li>
		    <li>Chasing: {{ squirrel.Chasing }}</li>
		    <li>Climbing: {{ squirrel.Climbing }}</li>
		    <li>Eating : {{ squirrel.Eating }}</li>
		    <li>Foraging: {{ squirrel.Foraging }}</li>
		    <li>Kuks: {{ squirrel.Kuks }}</li>
		    <li>Quaas: {{ squirrel.Quaas }}</li>
		    <li>Moans: {{ squirrel.Moans }}</li>
		    <li>Tail Flags: {{ squirrel.Tail_Flags }}</li>
		    <li>Tail Twitch: {{ squirrel.Tail_Twitches }}</li>
		    <li>Approaches: {{ squirrel.Approaches }}</li>
		    <li>Indifferent: {{  squirrel.Indifferent }} </li>
		    <li>Runs From: {{ squirrel.Runs_From }}</li>
	    </ul>
	    </p>
	<ul>

	    <li><a href="{% url 'sightings:detail' squirrel.Squirrel_ID %}">{{ squirrel.Squirrel_ID }}</a></li>

	</ul>
    {% endfor %}
    </body>
<html>

sightings/templates/sightings/edit.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Edit detail of sighting</title>
    </head>
    <body>       
	       
    <h3>Edit detail of sighting: {{ squirrel_id }}</h3>
	<form method="post">{% csrf_token %}
		{{form.as_p}}
		<br>
		<input type="submit" name="Submit" value="Submit">
        <input type="button" value="Back" onclick="document.location.href = '{% url 'sightings:index' %}'">
	</form>
    {% if success %}
        <p style="color: red">Saved successfully</p>
    {% endif %}
    </body>
</html>

sightings/templates/sightings/index.html
<!doctype html>
<html lang="en">
    <head>
        <title>Squirrel Tracker</title>
    </head>
    <body>
    <h1> Welcome to the Squirrel Tracking Website</h1>
	<img src="https://i.pinimg.com/564x/21/fd/41/21fd410d4ef6371f0264af5b6aa28700.jpg" alt="Squirrel Pictures">

	<h3>To add a new squirrel and create a new sightings in Database: </h3>
    <ul>	  
    	<a href="add/"> Add </a>
	</ul>	

	<h3>To view some general stats of our squirrels in Database:</h3>	
	<ul>				
    	<a href="stats/"> Stats </a>
	</ul>	

	<h3>Current Squirrels in Database:</h3>
	<table>
    <thead>
    <tr>
        <th>Unique Squirrel ID</th>
        <th>Date</th>
        <th>Link to update this squirrel</th>
    </tr>
    </thead>
    <tbody>
    {% for squirrel in squirrels %}
        <tr>
            <td style="text-align:center">{{ squirrel.Squirrel_ID }}</td>
            <td style="text-align:center">{{ squirrel.Date }}</td>
            <td style="text-align:center">
            <a href="{% url 'sightings:detail' squirrel.Squirrel_ID %}">Update<{{ squirrel.Squirrel_ID }}></a>
            </td>
            </tr>
    {% endfor %}
    </tbody>
</table>

    </body>
</html>

sightings/templates/sightings/map.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin=""></script>

    <style>
      html,body {
        height: 100%;
      }
    </style>
    <title>Squirrel Map</title>
  </head>
  <body>
    <div id="map" class="container-fluid h-100"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Leaflet JS -->
    <script>
        var map_center = [
            40.782091,  // Latitude
            -73.964285  // Longitude
        ];
        var zoom_level = 14;
        var map = L.map('map').setView(map_center, zoom_level);
        L.tileLayer('https://{server}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            server: 'a',  // can be 'a', 'b', or 'c'
            // must leave attribution in!
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(map);

        <!-- L.Icon.Default.prototype.options.iconSize = 15; -->
        <!-- L.Icon.Default.prototype.options.iconAnchor = [0, 0]; -->
        <!-- L.Icon.Default.prototype.options.shadowSize = 15; -->
        <!-- L.Icon.Default.prototype.options.shadowAnchor = [0, 0]; -->

        {% for sighting in sightings %}
          var point_lat_lon = [{{ sighting.Y }}, {{ sighting.X }}];
          var marker = L.marker(point_lat_lon).addTo(map);
        {% endfor %}
    </script>
  </body>
</html>

sightings/templates/sightings/stats.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Stats of squirrels</title>
</head>
<style>
table, th, td {
    border: 1px solid black;
}
</style>
<body>
<h2>Stats of squirrels</h2>
<input type="button" value="Back" onclick="document.location.href = '{% url 'sightings:index' %}'">

<h3>The general stats:</h3>
<table>
    <thead>
    <tr>
        <th>Total number of squirrels</th>
        <th>Age</th>
        <th>Date</th>
        <th>Shift</th>
        <th>Location</th>
        <th>Primary Fur Color</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td style="text-align:center">{{data_count}}</td>
            <td style="text-align:center">
            <br>Adults:{{Age_Adult_count}}<br/>
            <br>Juvenile:{{Age_Juvenile_count}}<br/>
            </td>
            <td style="text-align:center">
            <br>Max:{{Date_max}}<br/>
            <br>Min:{{Date_min}}<br/>            
            </td>
            <td style="text-align:center">
            <br>AM:{{Shift_AM_count}}<br/>
            <br>PM:{{Shift_PM_count}}<br/>
            </td>
            <td style="text-align:center">
            <br>Ground Plane:{{Location_GP_count}}<br/>
            <br>Above Ground:{{Location_AG_count}}<br/>
            </td>
            <td style="text-align:center">
            <br>Gray:{{Color_Gray_count}}<br/>
            <br>Cinnamon:{{Color_Cinnamon_count}}<br/>
            <br>Black:{{Color_Black_count}}<br/>
            </td>
            </tr>
    </tbody>
</table>
	
<h3>The detailed information:</h3>
<table>
    <thead>
    <tr>
        <th>Unique Squirrel ID</th>
        <th>Logitude</th>
        <th>Latitude</th>
        <th>Shift</th>       
        <th>Age</th>
        <th>Date</th>
        <th>Primary Fur Color</th>
        <th>Location</th>
        <th>Running</th>
        <th>Chasing</th>       
        <th>Climbing</th>
        <th>Eating</th>
        <th>Foraging</th>
        <th>Kuks</th>
        <th>Quaas</th>
        <th>Moans</th>       
        <th>Tail Flags</th>
        <th>Tail Twitch</th>
        <th>Approaches</th>
        <th>Indifferent</th>
        <th>Runs From</th>
    </tr>
    </thead>
    <tbody>
    {% for squirrel in squirrels %}
        <tr>
            <td style="text-align:center">{{ squirrel.Squirrel_ID }}</td>
            <td style="text-align:center">{{ squirrel.X }}</td>
            <td style="text-align:center">{{ squirrel.Y }}</td> 
            <td style="text-align:center">{{ squirrel.Shift }}</td>           
            <td style="text-align:center">{{ squirrel.Age }}</td>
            <td style="text-align:center">{{ squirrel.Date }}</td>
            <td style="text-align:center">{{ squirrel.Primary_Fur_Color }}</td>
            <td style="text-align:center">{{ squirrel.Location }}</td>
            <td style="text-align:center">{{ squirrel.Running }}</td>
            <td style="text-align:center">{{ squirrel.Chasing }}</td>            
            <td style="text-align:center">{{ squirrel.Climbing }}</td>
            <td style="text-align:center">{{ squirrel.Eating }}</td>
            <td style="text-align:center">{{ squirrel.Foraging }}</td>
            <td style="text-align:center">{{ squirrel.Kuks }}</td>
            <td style="text-align:center">{{ squirrel.Quaas }}</td>
            <td style="text-align:center">{{ squirrel.Moans }}</td>
            <td style="text-align:center">{{ squirrel.Tail_Flags }}</td>
            <td style="text-align:center">{{ squirrel.Tail_Twitches }}</td>            
            <td style="text-align:center">{{ squirrel.Approaches }}</td>
            <td style="text-align:center">{{ squirrel.Indifferent }}</td>
            <td style="text-align:center">{{ squirrel.Runs_From }}</td>
            </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>